version: '3'

networks: 
    laravel:
        driver: bridge

services: 
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8001:8001"
        volumes: 
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/app/public
        depends_on: 
            - php
            - mysql
        networks: 
            - laravel

    mysql:
        platform: linux/amd64
        image: mysql
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "${MYSQL_HOST_PORT}:${MYSQL_DOCKER_CONTAINER_PORT}"
        volumes: 
            - ./docker/mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: sismark
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes: 
            - .:/var/www/app
        ports: 
            - "${PHP_HOST_PORT}:${PHP_DOCKER_CONTAINER_PORT}"
        networks: 
            - laravel